spring:
  application:
    name: idrd-sports-api
  datasource:
    url: jdbc:sqlite:idrd_sports_mvp.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
